// src/Web3/Config.js - Auto-generated by deployment script
// Generated: 2026-01-02T06:34:25.862Z

export const NFT_ADDRESS = "0xC40f17FfF5591dbb12CD4279111C22bb33425244";
export const MARKETPLACE_ADDRESS = "0x2E3Ae1bC661C170D009Cf3E9686dFFfF60AEDc0b";
export const CHAIN_ID = 13473; // immutable

// NFT ABI (Essential functions only)
export const NFT_ABI = [
  "constructor()",
  "error ERC721IncorrectOwner(address,uint256,address)",
  "error ERC721InsufficientApproval(address,uint256)",
  "error ERC721InvalidApprover(address)",
  "error ERC721InvalidOperator(address)",
  "error ERC721InvalidOwner(address)",
  "error ERC721InvalidReceiver(address)",
  "error ERC721InvalidSender(address)",
  "error ERC721NonexistentToken(uint256)",
  "error OwnableInvalidOwner(address)",
  "error OwnableUnauthorizedAccount(address)",
  "event Approval(address indexed,address indexed,uint256 indexed)",
  "event ApprovalForAll(address indexed,address indexed,bool)",
  "event BatchMetadataUpdate(uint256,uint256)",
  "event FirstSaleCompleted(uint256 indexed)",
  "event MarketplaceAuthorized(address indexed,bool)",
  "event MetadataUpdate(uint256)",
  "event Minted(address indexed,uint256,string,uint16)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event Transfer(address indexed,address indexed,uint256 indexed)",
  "function approve(address,uint256)",
  "function authorizedMarketplaces(address) view returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function getApproved(uint256) view returns (address)",
  "function getCreator(uint256) view returns (address)",
  "function getRoyaltyInfo(uint256) view returns (address,uint16,bool)",
  "function hasBeenSold(uint256) view returns (bool)",
  "function isApprovedForAll(address,address) view returns (bool)",
  "function isMarketplaceAuthorized(address) view returns (bool)",
  "function markAsSold(uint256)",
  "function mint(string,uint16) returns (uint256)",
  "function name() view returns (string)",
  "function nextTokenId() view returns (uint256)",
  "function owner() view returns (address)",
  "function ownerOf(uint256) view returns (address)",
  "function renounceOwnership()",
  "function safeTransferFrom(address,address,uint256)",
  "function safeTransferFrom(address,address,uint256,bytes)",
  "function setApprovalForAll(address,bool)",
  "function setMarketplaceAuthorization(address,bool)",
  "function supportsInterface(bytes4) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenRoyalties(uint256) view returns (address,uint16)",
  "function tokenURI(uint256) view returns (string)",
  "function transferFrom(address,address,uint256)",
  "function transferOwnership(address)"
];

// Marketplace ABI (Essential functions only)
export const MARKETPLACE_ABI = [
  "constructor(address)",
  "error ReentrancyGuardReentrantCall()",
  "event ListingCancelled(address indexed,address indexed,uint256 indexed)",
  "event ListingCreated(address indexed,address indexed,uint256 indexed,uint256)",
  "event NFTSold(address indexed,address indexed,address indexed,uint256,uint256,uint256,uint256,uint256,bool)",
  "function PLATFORM_FEE_BPS() view returns (uint16)",
  "function buyNFT(address,uint256) payable",
  "function cancelListing(address,uint256)",
  "function createListing(address,uint256,uint256)",
  "function emergencyCancelListing(address,uint256)",
  "function getListing(address,uint256) view returns (address,uint256,bool)",
  "function listings(address,uint256) view returns (address,uint256,bool)",
  "function platformWallet() view returns (address)",
  "function updatePlatformWallet(address)"
];
